# Config for QuantizationRecipe in quantize.py
#
# To launch, run the following command from root torchtune directory:
#    tune run quantize --config quantization

#
# Model arguments
model:
  _component_: torchtune.models.mistral.mistral_classifier_7b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Mistral-7B-v0.1/reward
  checkpoint_files: [
    hf_model_0001_0.pt,
    hf_model_0002_0.pt,
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Mistral-7B-v0.1/reward/quant
  model_type: MISTRAL

device: cuda
dtype: bf16
seed: 1234

quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyQuantizer
  groupsize: 256
